[project]
name = "pysimplefin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "niquests>=3.15.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
